@extends('layouts.app')
@section('title','Admin Competitive | Warqnaa R12')
@section('content')
@php $local=fn($v)=>is_array($v)?($v[app()->getLocale()]??$v['ar']??$v['en']??reset($v)):$v; @endphp
<div class="r12-admin">
 <header class="r12-admin-hero"><div><span class="r12-live"><i></i> R12 • BUILD 240 • CONTROL PLANE</span><h1>♛ Admin Competitive Arena</h1><p>Seasons · MMR · Ranked queues · Integrity review · Leagues · Cups · Rewards</p></div><div class="r12-admin-badge">🛡️ AUDITED ACTIONS</div></header>
 <section class="r12-admin-stats">
  <div><small>Active seasons</small><b>{{$stats['active_seasons']}}</b></div><div><small>Queue waiting</small><b>{{$stats['ranked_waiting']}}</b></div><div><small>Live matches</small><b>{{$stats['matches_live']}}</b></div><div><small>Integrity review</small><b>{{$stats['matches_review']}}</b></div><div><small>Rated players</small><b>{{$stats['rated_players']}}</b></div><div><small>Open tournaments</small><b>{{$stats['tournaments_open']}}</b></div>
 </section>
 <div class="r12-admin-grid">
  <section class="r12-admin-panel"><h2>⚙ Competitive switches</h2><form method="post" action="{{route('admin.competitive.settings')}}">@csrf @method('patch')
   @foreach(['competitive_enabled'=>'Competitive Arena','ranked_matchmaking_enabled'=>'Ranked matchmaking','season_rewards_enabled'=>'Season rewards','club_championships_enabled'=>'Club championships','country_championships_enabled'=>'Country championships'] as $key=>$label)<label class="r12-switch"><input type="hidden" name="{{$key}}" value="0"><input type="checkbox" name="{{$key}}" value="1" @checked($settings[$key])><span>{{$label}}</span></label>@endforeach
   <label>Queue timeout (minutes)<input type="number" name="ranked_queue_timeout_minutes" min="2" max="60" value="{{$settings['ranked_queue_timeout_minutes']}}"></label><label>Abandon penalty<input type="number" name="ranked_abandon_penalty" min="0" max="250" value="{{$settings['ranked_abandon_penalty']}}"></label><button class="r12-primary">Save control plane</button>
  </form></section>
  <section class="r12-admin-panel"><h2>✦ Create season</h2><form method="post" action="{{route('admin.competitive.season.create')}}">@csrf
   <label>Season key<input name="key" value="season_{{now()->format('Y_m')}}" required></label><label>الاسم العربي<input name="name_ar" value="موسم أبطال ورقنا" required></label><label>English name<input name="name_en" value="Warqnaa Champions Season"></label><label>Starts<input type="datetime-local" name="starts_at" value="{{now()->addDay()->format('Y-m-d\TH:i')}}" required></label><label>Ends<input type="datetime-local" name="ends_at" value="{{now()->addDays(91)->format('Y-m-d\TH:i')}}" required></label><label>Soft reset factor<input type="number" name="rating_soft_reset_factor" min="0" max="1" step=".05" value=".75"></label><label>Placement games<input type="number" name="placement_games" min="1" max="30" value="10"></label><button class="r12-primary">Create audited season</button>
  </form></section>
  <section class="r12-admin-panel full"><h2>◷ Season lifecycle</h2><div class="r12-admin-table"><table><thead><tr><th>Season</th><th>Status</th><th>Window</th><th>Ratings</th><th>Matches</th><th>Rewards</th><th>Action</th></tr></thead><tbody>@foreach($seasons as $season)<tr><td><b>{{$local($season->name)}}</b><small style="display:block">{{$season->key}}</small></td><td>{{$season->status}}</td><td>{{$season->starts_at?->format('Y-m-d')}} → {{$season->ends_at?->format('Y-m-d')}}</td><td>{{$season->ratings_count}}</td><td>{{$season->matches_count}}</td><td>{{$season->reward_claims_count}}</td><td><form class="r12-inline-actions" method="post" action="{{route('admin.competitive.season.action',$season)}}">@csrf<select name="action"><option value="activate">Activate</option><option value="finalize">Finalize + rewards</option><option value="cancel">Cancel</option></select><button>Apply</button></form></td></tr>@endforeach</tbody></table></div></section>
  <section class="r12-admin-panel"><h2>🏆 Create championship</h2><form method="post" action="{{route('admin.competitive.tournament.create')}}">@csrf
   <label>Key<input name="key" value="cup_{{now()->format('Ymd_Hi')}}" required></label><label>الاسم العربي<input name="name_ar" value="كأس أبطال ورقنا" required></label><label>English name<input name="name_en" value="Warqnaa Champions Cup"></label><label>Game<select name="game_id">@foreach($games as $game)<option value="{{$game->id}}">{{$local($game->name)}} · {{$game->key}}</option>@endforeach</select></label><label>Format<select name="format"><option value="single_elimination">Single elimination</option><option value="league_playoffs">Season league ladder + playoffs</option><option value="group_playoffs">Group qualification + playoffs</option></select></label><label>Scope<select name="scope"><option value="global">Global</option><option value="club">Club</option><option value="country">Country</option></select></label><label>Club ID (scope=club)<input name="club_id" type="number" min="1" placeholder="12"></label><label>Country (scope=country)<input name="country_code" maxlength="2" placeholder="PS"></label><label>Stages<input type="number" name="stages" min="1" max="6" value="3"></label><label>Seats per match<input type="number" name="seats_per_match" min="2" max="6" value="4"></label><label>Entry tokens<input type="number" name="entry_fee" min="0" value="0"></label><label>Prize pool<input type="number" name="prize_pool" min="0" value="25000"></label><label>Min MMR<input type="number" name="min_rating" min="0" value="900"></label><label>Starts<input type="datetime-local" name="starts_at" value="{{now()->addDays(7)->format('Y-m-d\TH:i')}}" required></label><label>Registration closes<input type="datetime-local" name="registration_closes_at" value="{{now()->addDays(6)->format('Y-m-d\TH:i')}}"></label><button class="r12-primary">Create championship</button>
  </form></section>
  <section class="r12-admin-panel"><h2>⌁ Manual MMR settlement</h2><p style="color:var(--r12-muted)">Every adjustment creates a synthetic immutable competitive match and two rating events.</p><form method="post" action="{{url('/admin/competitive/ratings')}}" onsubmit="this.action=this.action+'/'+this.user_id.value">@csrf<label>User ID<input name="user_id" type="number" min="1" required></label><label>Game<select name="game_id">@foreach($games as $game)<option value="{{$game->id}}">{{$game->key}}</option>@endforeach</select></label><label>Delta<input name="delta" type="number" min="-500" max="500" value="25" required></label><label>Audit reason<textarea name="reason" required>Verified support settlement</textarea></label><button class="r12-primary">Apply audited adjustment</button></form></section>
  <section class="r12-admin-panel full"><h2>🛡 Integrity review queue</h2><div class="r12-admin-table"><table><thead><tr><th>Match</th><th>Game</th><th>Room</th><th>Mode</th><th>Anti-cheat</th><th>Action</th></tr></thead><tbody>@forelse($review_matches as $match)<tr><td>{{$match->match_key}}</td><td>{{$match->game?->key}}</td><td>{{$match->room?->code}}</td><td>{{$match->mode}}</td><td>{{$match->anti_cheat_status}}</td><td><form class="r12-inline-actions" method="post" action="{{route('admin.competitive.match.action',$match)}}">@csrf<select name="action"><option value="approve">Approve result</option><option value="void">Void match</option></select><input name="reason" value="Integrity review completed" required><button>Resolve</button></form></td></tr>@empty<tr><td colspan="6">✓ No matches waiting for integrity review.</td></tr>@endforelse</tbody></table></div></section>
  <section class="r12-admin-panel full"><h2>♜ Tournament brackets</h2><div class="r12-admin-table"><table><thead><tr><th>Tournament</th><th>Scope</th><th>Format</th><th>Players</th><th>Round</th><th>Status</th><th>Build</th></tr></thead><tbody>@foreach($tournaments as $tournament)<tr><td><b>{{$local($tournament->name) ?: $tournament->key}}</b><small style="display:block">#{{$tournament->id}} · {{$tournament->game?->key}}</small></td><td>{{$tournament->scope}}</td><td>{{$tournament->format}}</td><td>{{$tournament->entries()->count()}}/{{$tournament->max_players}}</td><td>{{$tournament->current_round}}/{{$tournament->stages}}</td><td>{{$tournament->status}}</td><td><form method="post" action="{{route('admin.competitive.tournament.bracket',$tournament)}}">@csrf<button>Build / resume</button></form></td></tr>@endforeach</tbody></table></div></section>
 </div>
</div>
@endsection
