<?php
return [
    'IS'=>['ar'=>'آيسلندا','en'=>'Iceland','flag'=>'🇮🇸'],
    'AZ'=>['ar'=>'أذربيجان','en'=>'Azerbaijan','flag'=>'🇦🇿'],
    'AM'=>['ar'=>'أرمينيا','en'=>'Armenia','flag'=>'🇦🇲'],
    'AW'=>['ar'=>'أروبا','en'=>'Aruba','flag'=>'🇦🇼'],
    'AU'=>['ar'=>'أستراليا','en'=>'Australia','flag'=>'🇦🇺'],
    'AF'=>['ar'=>'أفغانستان','en'=>'Afghanistan','flag'=>'🇦🇫'],
    'AL'=>['ar'=>'ألبانيا','en'=>'Albania','flag'=>'🇦🇱'],
    'DE'=>['ar'=>'ألمانيا','en'=>'Germany','flag'=>'🇩🇪'],
    'AQ'=>['ar'=>'أنتاركتيكا','en'=>'Antarctica','flag'=>'🇦🇶'],
    'AG'=>['ar'=>'أنتيغوا وبربودا','en'=>'Antigua & Barbuda','flag'=>'🇦🇬'],
    'AD'=>['ar'=>'أندورا','en'=>'Andorra','flag'=>'🇦🇩'],
    'AO'=>['ar'=>'أنغولا','en'=>'Angola','flag'=>'🇦🇴'],
    'AI'=>['ar'=>'أنغويلا','en'=>'Anguilla','flag'=>'🇦🇮'],
    'UY'=>['ar'=>'أورغواي','en'=>'Uruguay','flag'=>'🇺🇾'],
    'UZ'=>['ar'=>'أوزبكستان','en'=>'Uzbekistan','flag'=>'🇺🇿'],
    'UG'=>['ar'=>'أوغندا','en'=>'Uganda','flag'=>'🇺🇬'],
    'UA'=>['ar'=>'أوكرانيا','en'=>'Ukraine','flag'=>'🇺🇦'],
    'IE'=>['ar'=>'أيرلندا','en'=>'Ireland','flag'=>'🇮🇪'],
    'ET'=>['ar'=>'إثيوبيا','en'=>'Ethiopia','flag'=>'🇪🇹'],
    'ER'=>['ar'=>'إريتريا','en'=>'Eritrea','flag'=>'🇪🇷'],
    'ES'=>['ar'=>'إسبانيا','en'=>'Spain','flag'=>'🇪🇸'],
    'EE'=>['ar'=>'إستونيا','en'=>'Estonia','flag'=>'🇪🇪'],
    'SZ'=>['ar'=>'إسواتيني','en'=>'Eswatini','flag'=>'🇸🇿'],
    'ID'=>['ar'=>'إندونيسيا','en'=>'Indonesia','flag'=>'🇮🇩'],
    'IR'=>['ar'=>'إيران','en'=>'Iran','flag'=>'🇮🇷'],
    'IT'=>['ar'=>'إيطاليا','en'=>'Italy','flag'=>'🇮🇹'],
    'PS'=>['ar'=>'فلسطين','en'=>'Palestinian Territories','flag'=>'🇵🇸'],
    'AR'=>['ar'=>'الأرجنتين','en'=>'Argentina','flag'=>'🇦🇷'],
    'JO'=>['ar'=>'الأردن','en'=>'Jordan','flag'=>'🇯🇴'],
    'TF'=>['ar'=>'الأقاليم الجنوبية الفرنسية','en'=>'French Southern Territories','flag'=>'🇹🇫'],
    'IO'=>['ar'=>'الإقليم البريطاني في المحيط الهندي','en'=>'British Indian Ocean Territory','flag'=>'🇮🇴'],
    'EC'=>['ar'=>'الإكوادور','en'=>'Ecuador','flag'=>'🇪🇨'],
    'AE'=>['ar'=>'الإمارات العربية المتحدة','en'=>'United Arab Emirates','flag'=>'🇦🇪'],
    'BH'=>['ar'=>'البحرين','en'=>'Bahrain','flag'=>'🇧🇭'],
    'BR'=>['ar'=>'البرازيل','en'=>'Brazil','flag'=>'🇧🇷'],
    'PT'=>['ar'=>'البرتغال','en'=>'Portugal','flag'=>'🇵🇹'],
    'BA'=>['ar'=>'البوسنة والهرسك','en'=>'Bosnia & Herzegovina','flag'=>'🇧🇦'],
    'CZ'=>['ar'=>'التشيك','en'=>'Czechia','flag'=>'🇨🇿'],
    'ME'=>['ar'=>'الجبل الأسود','en'=>'Montenegro','flag'=>'🇲🇪'],
    'DZ'=>['ar'=>'الجزائر','en'=>'Algeria','flag'=>'🇩🇿'],
    'DK'=>['ar'=>'الدانمرك','en'=>'Denmark','flag'=>'🇩🇰'],
    'CV'=>['ar'=>'الرأس الأخضر','en'=>'Cape Verde','flag'=>'🇨🇻'],
    'SV'=>['ar'=>'السلفادور','en'=>'El Salvador','flag'=>'🇸🇻'],
    'SN'=>['ar'=>'السنغال','en'=>'Senegal','flag'=>'🇸🇳'],
    'SD'=>['ar'=>'السودان','en'=>'Sudan','flag'=>'🇸🇩'],
    'SE'=>['ar'=>'السويد','en'=>'Sweden','flag'=>'🇸🇪'],
    'EH'=>['ar'=>'الصحراء الغربية','en'=>'Western Sahara','flag'=>'🇪🇭'],
    'SO'=>['ar'=>'الصومال','en'=>'Somalia','flag'=>'🇸🇴'],
    'CN'=>['ar'=>'الصين','en'=>'China','flag'=>'🇨🇳'],
    'IQ'=>['ar'=>'العراق','en'=>'Iraq','flag'=>'🇮🇶'],
    'GA'=>['ar'=>'الغابون','en'=>'Gabon','flag'=>'🇬🇦'],
    'VA'=>['ar'=>'الفاتيكان','en'=>'Vatican City','flag'=>'🇻🇦'],
    'PH'=>['ar'=>'الفلبين','en'=>'Philippines','flag'=>'🇵🇭'],
    'CM'=>['ar'=>'الكاميرون','en'=>'Cameroon','flag'=>'🇨🇲'],
    'CG'=>['ar'=>'الكونغو - برازافيل','en'=>'Congo - Brazzaville','flag'=>'🇨🇬'],
    'CD'=>['ar'=>'الكونغو - كينشاسا','en'=>'Congo - Kinshasa','flag'=>'🇨🇩'],
    'KW'=>['ar'=>'الكويت','en'=>'Kuwait','flag'=>'🇰🇼'],
    'MA'=>['ar'=>'المغرب','en'=>'Morocco','flag'=>'🇲🇦'],
    'MX'=>['ar'=>'المكسيك','en'=>'Mexico','flag'=>'🇲🇽'],
    'SA'=>['ar'=>'المملكة العربية السعودية','en'=>'Saudi Arabia','flag'=>'🇸🇦'],
    'GB'=>['ar'=>'المملكة المتحدة','en'=>'United Kingdom','flag'=>'🇬🇧'],
    'NO'=>['ar'=>'النرويج','en'=>'Norway','flag'=>'🇳🇴'],
    'AT'=>['ar'=>'النمسا','en'=>'Austria','flag'=>'🇦🇹'],
    'NE'=>['ar'=>'النيجر','en'=>'Niger','flag'=>'🇳🇪'],
    'IN'=>['ar'=>'الهند','en'=>'India','flag'=>'🇮🇳'],
    'US'=>['ar'=>'الولايات المتحدة','en'=>'United States','flag'=>'🇺🇸'],
    'JP'=>['ar'=>'اليابان','en'=>'Japan','flag'=>'🇯🇵'],
    'YE'=>['ar'=>'اليمن','en'=>'Yemen','flag'=>'🇾🇪'],
    'GR'=>['ar'=>'اليونان','en'=>'Greece','flag'=>'🇬🇷'],
    'PG'=>['ar'=>'بابوا غينيا الجديدة','en'=>'Papua New Guinea','flag'=>'🇵🇬'],
    'PY'=>['ar'=>'باراغواي','en'=>'Paraguay','flag'=>'🇵🇾'],
    'PK'=>['ar'=>'باكستان','en'=>'Pakistan','flag'=>'🇵🇰'],
    'PW'=>['ar'=>'بالاو','en'=>'Palau','flag'=>'🇵🇼'],
    'BB'=>['ar'=>'بربادوس','en'=>'Barbados','flag'=>'🇧🇧'],
    'BM'=>['ar'=>'برمودا','en'=>'Bermuda','flag'=>'🇧🇲'],
    'BN'=>['ar'=>'بروناي','en'=>'Brunei','flag'=>'🇧🇳'],
    'BE'=>['ar'=>'بلجيكا','en'=>'Belgium','flag'=>'🇧🇪'],
    'BG'=>['ar'=>'بلغاريا','en'=>'Bulgaria','flag'=>'🇧🇬'],
    'BZ'=>['ar'=>'بليز','en'=>'Belize','flag'=>'🇧🇿'],
    'BD'=>['ar'=>'بنغلاديش','en'=>'Bangladesh','flag'=>'🇧🇩'],
    'PA'=>['ar'=>'بنما','en'=>'Panama','flag'=>'🇵🇦'],
    'BJ'=>['ar'=>'بنين','en'=>'Benin','flag'=>'🇧🇯'],
    'BT'=>['ar'=>'بوتان','en'=>'Bhutan','flag'=>'🇧🇹'],
    'BW'=>['ar'=>'بوتسوانا','en'=>'Botswana','flag'=>'🇧🇼'],
    'PR'=>['ar'=>'بورتوريكو','en'=>'Puerto Rico','flag'=>'🇵🇷'],
    'BF'=>['ar'=>'بوركينا فاسو','en'=>'Burkina Faso','flag'=>'🇧🇫'],
    'BI'=>['ar'=>'بوروندي','en'=>'Burundi','flag'=>'🇧🇮'],
    'PL'=>['ar'=>'بولندا','en'=>'Poland','flag'=>'🇵🇱'],
    'BO'=>['ar'=>'بوليفيا','en'=>'Bolivia','flag'=>'🇧🇴'],
    'PF'=>['ar'=>'بولينيزيا الفرنسية','en'=>'French Polynesia','flag'=>'🇵🇫'],
    'PE'=>['ar'=>'بيرو','en'=>'Peru','flag'=>'🇵🇪'],
    'BY'=>['ar'=>'بيلاروس','en'=>'Belarus','flag'=>'🇧🇾'],
    'TH'=>['ar'=>'تايلاند','en'=>'Thailand','flag'=>'🇹🇭'],
    'TW'=>['ar'=>'تايوان','en'=>'Taiwan','flag'=>'🇹🇼'],
    'TM'=>['ar'=>'تركمانستان','en'=>'Turkmenistan','flag'=>'🇹🇲'],
    'TR'=>['ar'=>'تركيا','en'=>'Türkiye','flag'=>'🇹🇷'],
    'TT'=>['ar'=>'ترينيداد وتوباغو','en'=>'Trinidad & Tobago','flag'=>'🇹🇹'],
    'TD'=>['ar'=>'تشاد','en'=>'Chad','flag'=>'🇹🇩'],
    'CL'=>['ar'=>'تشيلي','en'=>'Chile','flag'=>'🇨🇱'],
    'TZ'=>['ar'=>'تنزانيا','en'=>'Tanzania','flag'=>'🇹🇿'],
    'TG'=>['ar'=>'توغو','en'=>'Togo','flag'=>'🇹🇬'],
    'TV'=>['ar'=>'توفالو','en'=>'Tuvalu','flag'=>'🇹🇻'],
    'TK'=>['ar'=>'توكيلاو','en'=>'Tokelau','flag'=>'🇹🇰'],
    'TN'=>['ar'=>'تونس','en'=>'Tunisia','flag'=>'🇹🇳'],
    'TO'=>['ar'=>'تونغا','en'=>'Tonga','flag'=>'🇹🇴'],
    'TL'=>['ar'=>'تيمور - ليشتي','en'=>'Timor-Leste','flag'=>'🇹🇱'],
    'JM'=>['ar'=>'جامايكا','en'=>'Jamaica','flag'=>'🇯🇲'],
    'GI'=>['ar'=>'جبل طارق','en'=>'Gibraltar','flag'=>'🇬🇮'],
    'AX'=>['ar'=>'جزر آلاند','en'=>'Åland Islands','flag'=>'🇦🇽'],
    'BS'=>['ar'=>'جزر البهاما','en'=>'Bahamas','flag'=>'🇧🇸'],
    'KM'=>['ar'=>'جزر القمر','en'=>'Comoros','flag'=>'🇰🇲'],
    'MQ'=>['ar'=>'جزر المارتينيك','en'=>'Martinique','flag'=>'🇲🇶'],
    'MV'=>['ar'=>'جزر المالديف','en'=>'Maldives','flag'=>'🇲🇻'],
    'UM'=>['ar'=>'جزر الولايات المتحدة النائية','en'=>'U.S. Outlying Islands','flag'=>'🇺🇲'],
    'PN'=>['ar'=>'جزر بيتكيرن','en'=>'Pitcairn Islands','flag'=>'🇵🇳'],
    'TC'=>['ar'=>'جزر توركس وكايكوس','en'=>'Turks & Caicos Islands','flag'=>'🇹🇨'],
    'SB'=>['ar'=>'جزر سليمان','en'=>'Solomon Islands','flag'=>'🇸🇧'],
    'FO'=>['ar'=>'جزر فارو','en'=>'Faroe Islands','flag'=>'🇫🇴'],
    'FK'=>['ar'=>'جزر فوكلاند','en'=>'Falkland Islands','flag'=>'🇫🇰'],
    'VI'=>['ar'=>'جزر فيرجن الأمريكية','en'=>'U.S. Virgin Islands','flag'=>'🇻🇮'],
    'VG'=>['ar'=>'جزر فيرجن البريطانية','en'=>'British Virgin Islands','flag'=>'🇻🇬'],
    'KY'=>['ar'=>'جزر كايمان','en'=>'Cayman Islands','flag'=>'🇰🇾'],
    'CK'=>['ar'=>'جزر كوك','en'=>'Cook Islands','flag'=>'🇨🇰'],
    'CC'=>['ar'=>'جزر كوكوس (كيلينغ)','en'=>'Cocos (Keeling) Islands','flag'=>'🇨🇨'],
    'MH'=>['ar'=>'جزر مارشال','en'=>'Marshall Islands','flag'=>'🇲🇭'],
    'MP'=>['ar'=>'جزر ماريانا الشمالية','en'=>'Northern Mariana Islands','flag'=>'🇲🇵'],
    'WF'=>['ar'=>'جزر والس وفوتونا','en'=>'Wallis & Futuna','flag'=>'🇼🇫'],
    'BV'=>['ar'=>'جزيرة بوفيه','en'=>'Bouvet Island','flag'=>'🇧🇻'],
    'CX'=>['ar'=>'جزيرة كريسماس','en'=>'Christmas Island','flag'=>'🇨🇽'],
    'IM'=>['ar'=>'جزيرة مان','en'=>'Isle of Man','flag'=>'🇮🇲'],
    'NF'=>['ar'=>'جزيرة نورفولك','en'=>'Norfolk Island','flag'=>'🇳🇫'],
    'HM'=>['ar'=>'جزيرة هيرد وجزر ماكدونالد','en'=>'Heard & McDonald Islands','flag'=>'🇭🇲'],
    'CF'=>['ar'=>'جمهورية أفريقيا الوسطى','en'=>'Central African Republic','flag'=>'🇨🇫'],
    'DO'=>['ar'=>'جمهورية الدومينيكان','en'=>'Dominican Republic','flag'=>'🇩🇴'],
    'ZA'=>['ar'=>'جنوب أفريقيا','en'=>'South Africa','flag'=>'🇿🇦'],
    'SS'=>['ar'=>'جنوب السودان','en'=>'South Sudan','flag'=>'🇸🇸'],
    'GE'=>['ar'=>'جورجيا','en'=>'Georgia','flag'=>'🇬🇪'],
    'GS'=>['ar'=>'جورجيا الجنوبية وجزر ساندويتش الجنوبية','en'=>'South Georgia & South Sandwich Islands','flag'=>'🇬🇸'],
    'DJ'=>['ar'=>'جيبوتي','en'=>'Djibouti','flag'=>'🇩🇯'],
    'JE'=>['ar'=>'جيرسي','en'=>'Jersey','flag'=>'🇯🇪'],
    'DM'=>['ar'=>'دومينيكا','en'=>'Dominica','flag'=>'🇩🇲'],
    'RW'=>['ar'=>'رواندا','en'=>'Rwanda','flag'=>'🇷🇼'],
    'RU'=>['ar'=>'روسيا','en'=>'Russia','flag'=>'🇷🇺'],
    'RO'=>['ar'=>'رومانيا','en'=>'Romania','flag'=>'🇷🇴'],
    'RE'=>['ar'=>'روينيون','en'=>'Réunion','flag'=>'🇷🇪'],
    'ZM'=>['ar'=>'زامبيا','en'=>'Zambia','flag'=>'🇿🇲'],
    'ZW'=>['ar'=>'زيمبابوي','en'=>'Zimbabwe','flag'=>'🇿🇼'],
    'CI'=>['ar'=>'ساحل العاج','en'=>'Côte d’Ivoire','flag'=>'🇨🇮'],
    'WS'=>['ar'=>'ساموا','en'=>'Samoa','flag'=>'🇼🇸'],
    'AS'=>['ar'=>'ساموا الأمريكية','en'=>'American Samoa','flag'=>'🇦🇸'],
    'BL'=>['ar'=>'سان بارتليمي','en'=>'St. Barthélemy','flag'=>'🇧🇱'],
    'PM'=>['ar'=>'سان بيير ومكويلون','en'=>'St. Pierre & Miquelon','flag'=>'🇵🇲'],
    'MF'=>['ar'=>'سان مارتن','en'=>'St. Martin','flag'=>'🇲🇫'],
    'SM'=>['ar'=>'سان مارينو','en'=>'San Marino','flag'=>'🇸🇲'],
    'VC'=>['ar'=>'سانت فنسنت وجزر غرينادين','en'=>'St. Vincent & Grenadines','flag'=>'🇻🇨'],
    'KN'=>['ar'=>'سانت كيتس ونيفيس','en'=>'St. Kitts & Nevis','flag'=>'🇰🇳'],
    'LC'=>['ar'=>'سانت لوسيا','en'=>'St. Lucia','flag'=>'🇱🇨'],
    'SX'=>['ar'=>'سانت مارتن','en'=>'Sint Maarten','flag'=>'🇸🇽'],
    'SH'=>['ar'=>'سانت هيلينا','en'=>'St. Helena','flag'=>'🇸🇭'],
    'ST'=>['ar'=>'ساو تومي وبرينسيبي','en'=>'São Tomé & Príncipe','flag'=>'🇸🇹'],
    'LK'=>['ar'=>'سريلانكا','en'=>'Sri Lanka','flag'=>'🇱🇰'],
    'SJ'=>['ar'=>'سفالبارد وجان ماين','en'=>'Svalbard & Jan Mayen','flag'=>'🇸🇯'],
    'SK'=>['ar'=>'سلوفاكيا','en'=>'Slovakia','flag'=>'🇸🇰'],
    'SI'=>['ar'=>'سلوفينيا','en'=>'Slovenia','flag'=>'🇸🇮'],
    'SG'=>['ar'=>'سنغافورة','en'=>'Singapore','flag'=>'🇸🇬'],
    'SY'=>['ar'=>'سوريا','en'=>'Syria','flag'=>'🇸🇾'],
    'SR'=>['ar'=>'سورينام','en'=>'Suriname','flag'=>'🇸🇷'],
    'CH'=>['ar'=>'سويسرا','en'=>'Switzerland','flag'=>'🇨🇭'],
    'SL'=>['ar'=>'سيراليون','en'=>'Sierra Leone','flag'=>'🇸🇱'],
    'SC'=>['ar'=>'سيشل','en'=>'Seychelles','flag'=>'🇸🇨'],
    'RS'=>['ar'=>'صربيا','en'=>'Serbia','flag'=>'🇷🇸'],
    'TJ'=>['ar'=>'طاجيكستان','en'=>'Tajikistan','flag'=>'🇹🇯'],
    'OM'=>['ar'=>'عُمان','en'=>'Oman','flag'=>'🇴🇲'],
    'GM'=>['ar'=>'غامبيا','en'=>'Gambia','flag'=>'🇬🇲'],
    'GH'=>['ar'=>'غانا','en'=>'Ghana','flag'=>'🇬🇭'],
    'GD'=>['ar'=>'غرينادا','en'=>'Grenada','flag'=>'🇬🇩'],
    'GL'=>['ar'=>'غرينلاند','en'=>'Greenland','flag'=>'🇬🇱'],
    'GT'=>['ar'=>'غواتيمالا','en'=>'Guatemala','flag'=>'🇬🇹'],
    'GP'=>['ar'=>'غوادلوب','en'=>'Guadeloupe','flag'=>'🇬🇵'],
    'GU'=>['ar'=>'غوام','en'=>'Guam','flag'=>'🇬🇺'],
    'GF'=>['ar'=>'غويانا الفرنسية','en'=>'French Guiana','flag'=>'🇬🇫'],
    'GY'=>['ar'=>'غيانا','en'=>'Guyana','flag'=>'🇬🇾'],
    'GG'=>['ar'=>'غيرنزي','en'=>'Guernsey','flag'=>'🇬🇬'],
    'GN'=>['ar'=>'غينيا','en'=>'Guinea','flag'=>'🇬🇳'],
    'GQ'=>['ar'=>'غينيا الاستوائية','en'=>'Equatorial Guinea','flag'=>'🇬🇶'],
    'GW'=>['ar'=>'غينيا بيساو','en'=>'Guinea-Bissau','flag'=>'🇬🇼'],
    'VU'=>['ar'=>'فانواتو','en'=>'Vanuatu','flag'=>'🇻🇺'],
    'FR'=>['ar'=>'فرنسا','en'=>'France','flag'=>'🇫🇷'],
    'VE'=>['ar'=>'فنزويلا','en'=>'Venezuela','flag'=>'🇻🇪'],
    'FI'=>['ar'=>'فنلندا','en'=>'Finland','flag'=>'🇫🇮'],
    'VN'=>['ar'=>'فيتنام','en'=>'Vietnam','flag'=>'🇻🇳'],
    'FJ'=>['ar'=>'فيجي','en'=>'Fiji','flag'=>'🇫🇯'],
    'CY'=>['ar'=>'قبرص','en'=>'Cyprus','flag'=>'🇨🇾'],
    'QA'=>['ar'=>'قطر','en'=>'Qatar','flag'=>'🇶🇦'],
    'KG'=>['ar'=>'قيرغيزستان','en'=>'Kyrgyzstan','flag'=>'🇰🇬'],
    'KZ'=>['ar'=>'كازاخستان','en'=>'Kazakhstan','flag'=>'🇰🇿'],
    'NC'=>['ar'=>'كاليدونيا الجديدة','en'=>'New Caledonia','flag'=>'🇳🇨'],
    'HR'=>['ar'=>'كرواتيا','en'=>'Croatia','flag'=>'🇭🇷'],
    'KH'=>['ar'=>'كمبوديا','en'=>'Cambodia','flag'=>'🇰🇭'],
    'CA'=>['ar'=>'كندا','en'=>'Canada','flag'=>'🇨🇦'],
    'CU'=>['ar'=>'كوبا','en'=>'Cuba','flag'=>'🇨🇺'],
    'CW'=>['ar'=>'كوراساو','en'=>'Curaçao','flag'=>'🇨🇼'],
    'KR'=>['ar'=>'كوريا الجنوبية','en'=>'South Korea','flag'=>'🇰🇷'],
    'KP'=>['ar'=>'كوريا الشمالية','en'=>'North Korea','flag'=>'🇰🇵'],
    'CR'=>['ar'=>'كوستاريكا','en'=>'Costa Rica','flag'=>'🇨🇷'],
    'CO'=>['ar'=>'كولومبيا','en'=>'Colombia','flag'=>'🇨🇴'],
    'KI'=>['ar'=>'كيريباتي','en'=>'Kiribati','flag'=>'🇰🇮'],
    'KE'=>['ar'=>'كينيا','en'=>'Kenya','flag'=>'🇰🇪'],
    'LV'=>['ar'=>'لاتفيا','en'=>'Latvia','flag'=>'🇱🇻'],
    'LA'=>['ar'=>'لاوس','en'=>'Laos','flag'=>'🇱🇦'],
    'LB'=>['ar'=>'لبنان','en'=>'Lebanon','flag'=>'🇱🇧'],
    'LU'=>['ar'=>'لوكسمبورغ','en'=>'Luxembourg','flag'=>'🇱🇺'],
    'LY'=>['ar'=>'ليبيا','en'=>'Libya','flag'=>'🇱🇾'],
    'LR'=>['ar'=>'ليبيريا','en'=>'Liberia','flag'=>'🇱🇷'],
    'LT'=>['ar'=>'ليتوانيا','en'=>'Lithuania','flag'=>'🇱🇹'],
    'LI'=>['ar'=>'ليختنشتاين','en'=>'Liechtenstein','flag'=>'🇱🇮'],
    'LS'=>['ar'=>'ليسوتو','en'=>'Lesotho','flag'=>'🇱🇸'],
    'MT'=>['ar'=>'مالطا','en'=>'Malta','flag'=>'🇲🇹'],
    'ML'=>['ar'=>'مالي','en'=>'Mali','flag'=>'🇲🇱'],
    'MY'=>['ar'=>'ماليزيا','en'=>'Malaysia','flag'=>'🇲🇾'],
    'YT'=>['ar'=>'مايوت','en'=>'Mayotte','flag'=>'🇾🇹'],
    'MG'=>['ar'=>'مدغشقر','en'=>'Madagascar','flag'=>'🇲🇬'],
    'EG'=>['ar'=>'مصر','en'=>'Egypt','flag'=>'🇪🇬'],
    'MK'=>['ar'=>'مقدونيا الشمالية','en'=>'North Macedonia','flag'=>'🇲🇰'],
    'MW'=>['ar'=>'ملاوي','en'=>'Malawi','flag'=>'🇲🇼'],
    'MO'=>['ar'=>'منطقة ماكاو الإدارية الخاصة','en'=>'Macao SAR China','flag'=>'🇲🇴'],
    'MN'=>['ar'=>'منغوليا','en'=>'Mongolia','flag'=>'🇲🇳'],
    'MR'=>['ar'=>'موريتانيا','en'=>'Mauritania','flag'=>'🇲🇷'],
    'MU'=>['ar'=>'موريشيوس','en'=>'Mauritius','flag'=>'🇲🇺'],
    'MZ'=>['ar'=>'موزمبيق','en'=>'Mozambique','flag'=>'🇲🇿'],
    'MD'=>['ar'=>'مولدوفا','en'=>'Moldova','flag'=>'🇲🇩'],
    'MC'=>['ar'=>'موناكو','en'=>'Monaco','flag'=>'🇲🇨'],
    'MS'=>['ar'=>'مونتسرات','en'=>'Montserrat','flag'=>'🇲🇸'],
    'MM'=>['ar'=>'ميانمار (بورما)','en'=>'Myanmar (Burma)','flag'=>'🇲🇲'],
    'FM'=>['ar'=>'ميكرونيزيا','en'=>'Micronesia','flag'=>'🇫🇲'],
    'NA'=>['ar'=>'ناميبيا','en'=>'Namibia','flag'=>'🇳🇦'],
    'NR'=>['ar'=>'ناورو','en'=>'Nauru','flag'=>'🇳🇷'],
    'NP'=>['ar'=>'نيبال','en'=>'Nepal','flag'=>'🇳🇵'],
    'NG'=>['ar'=>'نيجيريا','en'=>'Nigeria','flag'=>'🇳🇬'],
    'NI'=>['ar'=>'نيكاراغوا','en'=>'Nicaragua','flag'=>'🇳🇮'],
    'NZ'=>['ar'=>'نيوزيلندا','en'=>'New Zealand','flag'=>'🇳🇿'],
    'NU'=>['ar'=>'نيوي','en'=>'Niue','flag'=>'🇳🇺'],
    'HT'=>['ar'=>'هايتي','en'=>'Haiti','flag'=>'🇭🇹'],
    'HN'=>['ar'=>'هندوراس','en'=>'Honduras','flag'=>'🇭🇳'],
    'HU'=>['ar'=>'هنغاريا','en'=>'Hungary','flag'=>'🇭🇺'],
    'NL'=>['ar'=>'هولندا','en'=>'Netherlands','flag'=>'🇳🇱'],
    'BQ'=>['ar'=>'هولندا الكاريبية','en'=>'Caribbean Netherlands','flag'=>'🇧🇶'],
    'HK'=>['ar'=>'هونغ كونغ الصينية (منطقة إدارية خاصة)','en'=>'Hong Kong SAR China','flag'=>'🇭🇰'],
];
