<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('friendships', function(Blueprint $t){$t->id();$t->foreignId('requester_id')->constrained('users')->cascadeOnDelete();$t->foreignId('addressee_id')->constrained('users')->cascadeOnDelete();$t->enum('status',['pending','accepted','rejected','blocked'])->default('pending');$t->timestamps();$t->unique(['requester_id','addressee_id']);});
  Schema::create('messages', function(Blueprint $t){$t->id();$t->foreignId('sender_id')->constrained('users')->cascadeOnDelete();$t->foreignId('receiver_id')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('room_id')->nullable()->constrained()->cascadeOnDelete();$t->text('body');$t->timestamps();});
  Schema::create('notifications', function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('type');$t->json('title');$t->json('body')->nullable();$t->string('url')->nullable();$t->boolean('read')->default(false);$t->json('meta')->nullable();$t->timestamps();});
  Schema::create('store_items', function(Blueprint $t){$t->id();$t->string('key')->unique();$t->json('name');$t->enum('category',['name_color','text_color','pasha','xp_booster','table','badge','card_back','name_frame','effect','emoji_pack']);$t->unsignedBigInteger('price');$t->unsignedInteger('duration_days')->nullable();$t->json('payload')->nullable();$t->boolean('active')->default(true);$t->timestamps();});
  Schema::create('inventory_items', function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('store_item_id')->constrained()->cascadeOnDelete();$t->boolean('active')->default(false);$t->timestamp('activated_at')->nullable();$t->timestamp('expires_at')->nullable();$t->timestamps();});
  Schema::create('clubs', function(Blueprint $t){$t->id();$t->foreignId('owner_id')->constrained('users')->cascadeOnDelete();$t->string('name')->unique();$t->unsignedTinyInteger('level')->default(1);$t->unsignedInteger('weekly_points')->default(0);$t->unsignedBigInteger('treasury')->default(0);$t->timestamps();});
  Schema::create('club_members', function(Blueprint $t){$t->id();$t->foreignId('club_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->enum('role',['owner','moderator','member'])->default('member');$t->json('permissions')->nullable();$t->unsignedInteger('weekly_points')->default(0);$t->timestamps();$t->unique(['club_id','user_id']);});
  Schema::create('tournaments', function(Blueprint $t){$t->id();$t->foreignId('creator_id')->constrained('users')->cascadeOnDelete();$t->foreignId('game_id')->constrained()->cascadeOnDelete();$t->unsignedTinyInteger('stages')->default(1);$t->unsignedTinyInteger('seats_per_match')->default(4);$t->unsignedBigInteger('entry_fee')->default(0);$t->unsignedBigInteger('prize_pool')->default(0);$t->enum('status',['open','running','finished','cancelled'])->default('open');$t->json('bracket')->nullable();$t->timestamps();});
 }
 public function down(): void {foreach(['tournaments','club_members','clubs','inventory_items','store_items','notifications','messages','friendships'] as $table) Schema::dropIfExists($table);}
};
