@extends('layouts.app')
@section('title','Replay '.$replay->room?->code.' | Warqnaa')
@section('content')
<div class="r11-viewer r11-replay-viewer">
  <header><div><span class="r11-kicker">↻ PRIVACY-SAFE REPLAY</span><h1>{{$replay->game?->name[app()->getLocale()] ?? $replay->game?->key}} • {{$replay->room?->code}}</h1><p>{{$replay->frames_count}} frames • {{gmdate('i:s',(int)$replay->duration_seconds)}} • SHA-256 {{$replay->sha256 ? substr($replay->sha256,0,12).'…' : '—'}}</p></div><a href="{{route('social-world')}}">← Social World</a></header>
  <div class="r11-privacy-banner">🛡️ <b>Replay Privacy Contract • SHA-256 Verified</b><span>No hands, voice, private chat or secret engine state is stored in this playback. The replay digest is verified before playback.</span></div>
  <section class="r11-replay-stage"><div class="r11-replay-action" id="r11ReplayAction">Ready</div><div class="r11-replay-phase"><span id="r11ReplayPhase">—</span><b id="r11ReplayTurn">—</b></div><pre id="r11ReplayState">{}</pre></section>
  <div class="r11-player-controls"><button id="r11ReplayBack">«</button><button id="r11ReplayPlay">▶</button><button id="r11ReplayNext">»</button><input id="r11ReplayRange" type="range" min="0" max="{{max(0,$replay->frames_count-1)}}" value="0"><output id="r11ReplayCount">0 / {{$replay->frames_count}}</output></div>
</div>
<script id="r11ReplayData" type="application/json">@json($payload)</script>
<script>document.addEventListener('DOMContentLoaded',()=>{const p=JSON.parse(document.getElementById('r11ReplayData')?.textContent||'{}'),f=p.frames||[];let i=0,t=null;const back=document.getElementById('r11ReplayBack'),play=document.getElementById('r11ReplayPlay'),next=document.getElementById('r11ReplayNext'),range=document.getElementById('r11ReplayRange');const render=()=>{const x=f[i]||{};document.getElementById('r11ReplayAction').textContent=x.action||'Ready';document.getElementById('r11ReplayPhase').textContent=x.phase_after||'—';document.getElementById('r11ReplayTurn').textContent=x.turn||'—';document.getElementById('r11ReplayState').textContent=JSON.stringify(x.state||{},null,2);range.value=f.length?i:0;document.getElementById('r11ReplayCount').value=`${f.length?i+1:0} / ${f.length}`;back.disabled=!f.length||i===0;next.disabled=!f.length||i>=f.length-1;play.disabled=!f.length};back.onclick=()=>{i=Math.max(0,i-1);render()};next.onclick=()=>{i=Math.min(Math.max(0,f.length-1),i+1);render()};range.oninput=e=>{i=+e.target.value;render()};play.onclick=e=>{if(t){clearInterval(t);t=null;e.target.textContent='▶'}else{e.target.textContent='Ⅱ';t=setInterval(()=>{if(i>=f.length-1){clearInterval(t);t=null;e.target.textContent='▶'}else{i++;render()}},900)}};render()});</script>
@endsection
