part of 'main.dart';

const String warqnaaWorldExperienceRelease = '1.1.0+300';
const List<String> v300SupportedLocaleCodes = <String>['ar', 'en', 'de', 'tr', 'fr', 'es'];

const Map<String, String> v300LocaleNames = <String, String>{
  'ar': 'العربية', 'en': 'English', 'de': 'Deutsch', 'tr': 'Türkçe', 'fr': 'Français', 'es': 'Español',
};

/// Customer-facing translations added by WORLD EXPERIENCE. Legacy keys that
/// are not present here continue through the existing English fallback so the
/// app never renders a raw translation key.
const Map<String, Map<String, String>> v300Translations = <String, Map<String, String>>{
  'ar': <String, String>{
    'worldHub':'مركز اللعب العالمي','quickMatch':'مباراة سريعة','party':'المجموعة','partyHint':'اجمع أصدقاءك وادخلوا المباراة معًا','spectate':'المشاهدة','spectateHint':'شاهد مباريات عامة بدون كشف أوراق اللاعبين','reconnect':'استعادة المباراة','reconnectHint':'عد إلى نفس المقعد خلال مهلة الاتصال','matchmaking':'البحث الذكي','afkProtection':'حماية الانقطاع','seasonal':'الموسم','economyAudit':'تدقيق الاقتصاد','securityCenter':'مركز الأمان','liveOps':'العمليات المباشرة','profileFrames':'إطارات البروفايل','haptics':'الاهتزازات','reduceMotion':'تقليل الحركة','worldExperience':'WORLD EXPERIENCE','onlineNow':'متصل الآن','createParty':'إنشاء مجموعة','myParty':'مجموعتي','inviteFriends':'دعوة الأصدقاء','leaveParty':'مغادرة المجموعة','matchFound':'تم العثور على مباراة','reconnecting':'جارٍ استعادة الاتصال','serverControl':'تحكم خادمي مؤقت','riskScore':'درجة المخاطر','auditQueue':'قائمة التدقيق','moderation':'الإشراف','analytics':'التحليلات','premiumHeroTitle':'طاولتك. عالمك. منافستك.','premiumHeroSubtitle':'لعب اجتماعي عالمي، محركات خادمية عادلة، منافسات وأصدقاء وتخصيص عميق في تجربة واحدة.','liveNetwork':'الشبكة المباشرة','serverFair':'عدالة خادمية','enterArena':'ادخل الساحة','worldStatus':'WORLD EXPERIENCE • B303',
  },
  'en': <String, String>{
    'worldHub':'World Play Hub','quickMatch':'Quick Match','party':'Party','partyHint':'Group with friends and enter matches together','spectate':'Spectate','spectateHint':'Watch public matches without exposing private hands','reconnect':'Reconnect','reconnectHint':'Return to the same seat inside the reconnect grace window','matchmaking':'Smart Matchmaking','afkProtection':'AFK Protection','seasonal':'Season','economyAudit':'Economy Audit','securityCenter':'Security Center','liveOps':'Live Ops','profileFrames':'Profile Frames','haptics':'Haptics','reduceMotion':'Reduce Motion','worldExperience':'WORLD EXPERIENCE','onlineNow':'Online now','createParty':'Create Party','myParty':'My Party','inviteFriends':'Invite Friends','leaveParty':'Leave Party','matchFound':'Match found','reconnecting':'Reconnecting','serverControl':'Temporary server control','riskScore':'Risk score','auditQueue':'Audit queue','moderation':'Moderation','analytics':'Analytics','premiumHeroTitle':'Your table. Your world. Your competition.','premiumHeroSubtitle':'Global social card gaming, fair server-authoritative engines, ranked competition, friends and deep customization in one experience.','liveNetwork':'Live network','serverFair':'Server fair play','enterArena':'Enter arena','worldStatus':'WORLD EXPERIENCE • B303',
  },
  'de': <String, String>{
    'home':'Start','games':'Spiele','store':'Shop','clubs':'Gruppen','events':'Wettbewerbe','social_world':'Community','welcome':'Willkommen zurück','level':'Level','coins':'Token','vip':'Pascha','days':'Tage','join':'Jetzt teilnehmen','featured':'Empfohlene Spiele','customize':'Anpassen','friendly':'Freundschaftsspiel','competitions':'Wettbewerbe','challenges':'Herausforderungen','friends':'Freunde','settings':'Einstellungen','language':'Sprache','theme':'Design','claim':'Abholen','buy':'Kaufen','owned':'Im Besitz','rules':'Regeln','leaderboard':'Bestenliste','chat':'Chat','quick':'Schnellreaktionen','yourTurn':'Du bist dran','play':'Spielen','pass':'Passen','bid':'Bieten','notifications':'Benachrichtigungen','rewards':'Belohnungen','transactions':'Token-Verlauf','inventory':'Inventar','createRoom':'Raum erstellen','normalGame':'Normales Spiel','voiceGame':'Sprachspiel','publicRoom':'Öffentlicher Raum','friendsRoom':'Nur Freunde','privateRoom':'Privater Raum','search':'Spiele suchen','members':'Mitglieder','profile':'Profil','logout':'Abmelden','appearance':'Darstellung','save':'Speichern','cancel':'Abbrechen','activate':'Aktivieren','worldHub':'Globales Spielzentrum','quickMatch':'Schnelles Match','party':'Gruppe','partyHint':'Mit Freunden gruppieren und gemeinsam spielen','spectate':'Zuschauen','spectateHint':'Öffentliche Spiele ansehen, ohne private Karten zu sehen','reconnect':'Wiederverbinden','reconnectHint':'Innerhalb der Frist auf denselben Platz zurückkehren','matchmaking':'Intelligente Spielersuche','afkProtection':'AFK-Schutz','seasonal':'Saison','economyAudit':'Wirtschaftsprüfung','securityCenter':'Sicherheitszentrum','liveOps':'Live-Betrieb','profileFrames':'Profilrahmen','haptics':'Haptik','reduceMotion':'Bewegung reduzieren','worldExperience':'WORLD EXPERIENCE','onlineNow':'Jetzt online','createParty':'Gruppe erstellen','myParty':'Meine Gruppe','inviteFriends':'Freunde einladen','leaveParty':'Gruppe verlassen','matchFound':'Spiel gefunden','reconnecting':'Verbindung wird wiederhergestellt','serverControl':'Temporäre Serversteuerung','riskScore':'Risikowert','auditQueue':'Prüfliste','moderation':'Moderation','analytics':'Analysen','premiumHeroTitle':'Dein Tisch. Deine Welt. Dein Wettbewerb.','premiumHeroSubtitle':'Globale soziale Kartenspiele mit fairen Server-Engines, Ranglisten, Freunden und tiefer Anpassung.','liveNetwork':'Live-Netzwerk','serverFair':'Server-Fairplay','enterArena':'Arena betreten','worldStatus':'WORLD EXPERIENCE • B303','tarneeb':'Tarneeb','trix':'Trix','hand':'Hand','banakil':'Banakil','baloot':'Baloot','basra':'Basra','tarneeb_400':'Tarneeb 400','syrian_tarneeb':'Syrisches Tarneeb','trix_complex':'Trix Complex','saudi_hand':'Saudi Hand','hand_partner':'Partner-Hand','trix_partner':'Partner-Trix',
  },
  'tr': <String, String>{
    'home':'Ana Sayfa','games':'Oyunlar','store':'Mağaza','clubs':'Gruplar','events':'Müsabakalar','social_world':'Topluluk','welcome':'Tekrar hoş geldin','level':'Seviye','coins':'Jeton','vip':'Paşa','days':'Gün','join':'Şimdi katıl','featured':'Öne Çıkan Oyunlar','customize':'Özelleştir','friendly':'Dostluk Maçı','competitions':'Müsabakalar','challenges':'Görevler','friends':'Arkadaşlar','settings':'Ayarlar','language':'Dil','theme':'Tema','claim':'Al','buy':'Satın Al','owned':'Sahip','rules':'Kurallar','leaderboard':'Liderlik Tablosu','chat':'Sohbet','quick':'Hızlı Tepkiler','yourTurn':'Sıra Sende','play':'Oyna','pass':'Pas','bid':'Teklif','notifications':'Bildirimler','rewards':'Ödüller','transactions':'Jeton Geçmişi','inventory':'Envanter','createRoom':'Oda Oluştur','normalGame':'Normal oyun','voiceGame':'Sesli oyun','publicRoom':'Herkese açık oda','friendsRoom':'Sadece arkadaşlar','privateRoom':'Özel oda','search':'Oyun ara','members':'üye','profile':'Profil','logout':'Çıkış','appearance':'Görünüm','save':'Kaydet','cancel':'İptal','activate':'Etkinleştir','worldHub':'Dünya Oyun Merkezi','quickMatch':'Hızlı Maç','party':'Ekip','partyHint':'Arkadaşlarınla ekip kur ve maça birlikte gir','spectate':'İzle','spectateHint':'Özel elleri görmeden açık maçları izle','reconnect':'Yeniden Bağlan','reconnectHint':'Süre içinde aynı koltuğa geri dön','matchmaking':'Akıllı Eşleştirme','afkProtection':'AFK Koruması','seasonal':'Sezon','economyAudit':'Ekonomi Denetimi','securityCenter':'Güvenlik Merkezi','liveOps':'Canlı Operasyon','profileFrames':'Profil Çerçeveleri','haptics':'Titreşim','reduceMotion':'Hareketi Azalt','worldExperience':'WORLD EXPERIENCE','onlineNow':'Şimdi çevrimiçi','createParty':'Ekip Oluştur','myParty':'Ekibim','inviteFriends':'Arkadaş Davet Et','leaveParty':'Ekipten Ayrıl','matchFound':'Maç bulundu','reconnecting':'Yeniden bağlanıyor','serverControl':'Geçici sunucu kontrolü','riskScore':'Risk puanı','auditQueue':'Denetim kuyruğu','moderation':'Moderasyon','analytics':'Analizler','premiumHeroTitle':'Masan. Dünyan. Rekabetin.','premiumHeroSubtitle':'Adil sunucu motorları, dereceli rekabet, arkadaşlar ve derin kişiselleştirme ile küresel kart deneyimi.','liveNetwork':'Canlı ağ','serverFair':'Sunucu adaleti','enterArena':'Arenaya gir','worldStatus':'WORLD EXPERIENCE • B303','tarneeb':'Tarneeb','trix':'Trix','hand':'Hand','banakil':'Banakil','baloot':'Baloot','basra':'Basra','tarneeb_400':'Tarneeb 400','syrian_tarneeb':'Suriye Tarneebi','trix_complex':'Trix Complex','saudi_hand':'Suudi Hand','hand_partner':'Eşli Hand','trix_partner':'Eşli Trix',
  },
  'fr': <String, String>{
    'home':'Accueil','games':'Jeux','store':'Boutique','clubs':'Groupes','events':'Compétitions','social_world':'Communauté','welcome':'Bon retour','level':'Niveau','coins':'Jetons','vip':'Pacha','days':'Jours','join':'Rejoindre','featured':'Jeux en vedette','customize':'Personnaliser','friendly':'Match amical','competitions':'Compétitions','challenges':'Défis','friends':'Amis','settings':'Paramètres','language':'Langue','theme':'Thème','claim':'Récupérer','buy':'Acheter','owned':'Possédé','rules':'Règles','leaderboard':'Classement','chat':'Discussion','quick':'Réactions rapides','yourTurn':'À vous','play':'Jouer','pass':'Passer','bid':'Enchérir','notifications':'Notifications','rewards':'Récompenses','transactions':'Historique des jetons','inventory':'Inventaire','createRoom':'Créer une salle','normalGame':'Partie normale','voiceGame':'Partie vocale','publicRoom':'Salle publique','friendsRoom':'Amis uniquement','privateRoom':'Salle privée','search':'Rechercher un jeu','members':'membres','profile':'Profil','logout':'Déconnexion','appearance':'Apparence','save':'Enregistrer','cancel':'Annuler','activate':'Activer','worldHub':'Centre de jeu mondial','quickMatch':'Partie rapide','party':'Groupe','partyHint':'Regroupez vos amis et entrez ensemble en partie','spectate':'Spectateur','spectateHint':'Regardez les parties publiques sans révéler les mains privées','reconnect':'Reconnexion','reconnectHint':'Revenez au même siège pendant le délai de reconnexion','matchmaking':'Matchmaking intelligent','afkProtection':'Protection AFK','seasonal':'Saison','economyAudit':'Audit économique','securityCenter':'Centre de sécurité','liveOps':'Opérations en direct','profileFrames':'Cadres de profil','haptics':'Retour haptique','reduceMotion':'Réduire les animations','worldExperience':'WORLD EXPERIENCE','onlineNow':'En ligne','createParty':'Créer un groupe','myParty':'Mon groupe','inviteFriends':'Inviter des amis','leaveParty':'Quitter le groupe','matchFound':'Partie trouvée','reconnecting':'Reconnexion en cours','serverControl':'Contrôle serveur temporaire','riskScore':'Score de risque','auditQueue':'File d’audit','moderation':'Modération','analytics':'Analyses','premiumHeroTitle':'Votre table. Votre monde. Votre compétition.','premiumHeroSubtitle':'Jeu de cartes social mondial, moteurs serveur équitables, classement, amis et personnalisation profonde.','liveNetwork':'Réseau en direct','serverFair':'Équité serveur','enterArena':'Entrer dans l’arène','worldStatus':'WORLD EXPERIENCE • B303','tarneeb':'Tarneeb','trix':'Trix','hand':'Hand','banakil':'Banakil','baloot':'Baloot','basra':'Basra','tarneeb_400':'Tarneeb 400','syrian_tarneeb':'Tarneeb syrien','trix_complex':'Trix Complex','saudi_hand':'Hand saoudien','hand_partner':'Hand en partenariat','trix_partner':'Trix en partenariat',
  },
  'es': <String, String>{
    'home':'Inicio','games':'Juegos','store':'Tienda','clubs':'Grupos','events':'Competiciones','social_world':'Comunidad','welcome':'Bienvenido de nuevo','level':'Nivel','coins':'Fichas','vip':'Pachá','days':'Días','join':'Unirse ahora','featured':'Juegos destacados','customize':'Personalizar','friendly':'Partida amistosa','competitions':'Competiciones','challenges':'Desafíos','friends':'Amigos','settings':'Ajustes','language':'Idioma','theme':'Tema','claim':'Recoger','buy':'Comprar','owned':'En propiedad','rules':'Reglas','leaderboard':'Clasificación','chat':'Chat','quick':'Reacciones rápidas','yourTurn':'Tu turno','play':'Jugar','pass':'Pasar','bid':'Pujar','notifications':'Notificaciones','rewards':'Recompensas','transactions':'Historial de fichas','inventory':'Inventario','createRoom':'Crear sala','normalGame':'Partida normal','voiceGame':'Partida con voz','publicRoom':'Sala pública','friendsRoom':'Solo amigos','privateRoom':'Sala privada','search':'Buscar juegos','members':'miembros','profile':'Perfil','logout':'Cerrar sesión','appearance':'Apariencia','save':'Guardar','cancel':'Cancelar','activate':'Activar','worldHub':'Centro de Juego Mundial','quickMatch':'Partida rápida','party':'Grupo','partyHint':'Reúne a tus amigos y entren juntos a las partidas','spectate':'Espectador','spectateHint':'Mira partidas públicas sin revelar manos privadas','reconnect':'Reconectar','reconnectHint':'Vuelve al mismo asiento durante el margen de reconexión','matchmaking':'Emparejamiento inteligente','afkProtection':'Protección AFK','seasonal':'Temporada','economyAudit':'Auditoría económica','securityCenter':'Centro de seguridad','liveOps':'Operaciones en vivo','profileFrames':'Marcos de perfil','haptics':'Respuesta háptica','reduceMotion':'Reducir movimiento','worldExperience':'WORLD EXPERIENCE','onlineNow':'En línea ahora','createParty':'Crear grupo','myParty':'Mi grupo','inviteFriends':'Invitar amigos','leaveParty':'Salir del grupo','matchFound':'Partida encontrada','reconnecting':'Reconectando','serverControl':'Control temporal del servidor','riskScore':'Nivel de riesgo','auditQueue':'Cola de auditoría','moderation':'Moderación','analytics':'Analíticas','premiumHeroTitle':'Tu mesa. Tu mundo. Tu competición.','premiumHeroSubtitle':'Juego social global con motores justos en servidor, ranking, amigos y personalización profunda.','liveNetwork':'Red en vivo','serverFair':'Juego justo del servidor','enterArena':'Entrar a la arena','worldStatus':'WORLD EXPERIENCE • B303','tarneeb':'Tarneeb','trix':'Trix','hand':'Hand','banakil':'Banakil','baloot':'Baloot','basra':'Basra','tarneeb_400':'Tarneeb 400','syrian_tarneeb':'Tarneeb sirio','trix_complex':'Trix Complex','saudi_hand':'Hand saudí','hand_partner':'Hand en pareja','trix_partner':'Trix en pareja',
  },
};

const List<String> v300EmojiLibrary = <String>[
  '😀','😄','😁','😂','🤣','😉','😍','🥰','😎','🤩','🥳','🤭','🫡','🤔','😴','🥺','😭','😡','🤬','😤',
  '👍','👎','👏','🙌','👌','🤝','🫶','💪','🙏','👑','🏆','🥇','💯','🔥','⚡','✨','💫','🎉','🎊','🎯',
  '♠️','♥️','♦️','♣️','🃏','🎲','🪄','💎','🌙','⭐','🌟','🌹','🕊️','☕','🫖','🧿','🫒','🦁','🦅','🐺','🐯','🐉','🦂','🦈','🚀','🌌','🪐','☄️','🇵🇸','🤍','❤️','💚','🖤'
];

const List<StoreProduct> v300WorldStoreProducts = <StoreProduct>[
  StoreProduct(id:'cover_world_aurora',category:'covers',icon:'🌌',nameAr:'غلاف الشفق العالمي',nameEn:'World Aurora Cover',descriptionAr:'غلاف متدرج هادئ للملف الشخصي.',descriptionEn:'Refined aurora profile cover.',price:22000,value:'cover_world_aurora',previewColor1:Color(0xff0f172a),previewColor2:Color(0xff7c3aed),collection:'world_2026'),
  StoreProduct(id:'cover_world_emerald',category:'covers',icon:'💚',nameAr:'غلاف زمرد النخبة',nameEn:'Elite Emerald Cover',descriptionAr:'غلاف زمردي احترافي.',descriptionEn:'Premium emerald profile cover.',price:24000,value:'cover_world_emerald',previewColor1:Color(0xff052e16),previewColor2:Color(0xff34d399),collection:'world_2026'),
  StoreProduct(id:'cover_world_sunset',category:'covers',icon:'🌅',nameAr:'غلاف غروب الملك',nameEn:'Royal Sunset Cover',descriptionAr:'غلاف غروب دافئ وفخم.',descriptionEn:'Warm premium sunset cover.',price:26000,value:'cover_world_sunset',previewColor1:Color(0xff431407),previewColor2:Color(0xfffb923c),collection:'world_2026'),
  StoreProduct(id:'cover_world_ocean',category:'covers',icon:'🌊',nameAr:'غلاف محيط عميق',nameEn:'Deep Ocean Cover',descriptionAr:'غلاف أزرق عميق.',descriptionEn:'Deep blue premium cover.',price:26000,value:'cover_world_ocean',previewColor1:Color(0xff082f49),previewColor2:Color(0xff38bdf8),collection:'world_2026'),
  StoreProduct(id:'cover_world_rose',category:'covers',icon:'🌹',nameAr:'غلاف ورد ملكي',nameEn:'Royal Rose Cover',descriptionAr:'غلاف وردي ملكي.',descriptionEn:'Royal rose profile cover.',price:28000,value:'cover_world_rose',previewColor1:Color(0xff4c0519),previewColor2:Color(0xfffb7185),collection:'world_2026'),
  StoreProduct(id:'cover_world_obsidian',category:'covers',icon:'🖤',nameAr:'غلاف أوبسيديان',nameEn:'Obsidian Cover',descriptionAr:'غلاف أسود فاخر.',descriptionEn:'Premium obsidian cover.',price:32000,value:'cover_world_obsidian',previewColor1:Color(0xff020617),previewColor2:Color(0xff64748b),collection:'world_2026'),
  StoreProduct(id:'cover_world_palestine',category:'covers',icon:'🇵🇸',nameAr:'غلاف فلسطين',nameEn:'Palestine Cover',descriptionAr:'هوية أنيقة مستوحاة من ألوان فلسطين.',descriptionEn:'Elegant identity inspired by Palestine colors.',price:30000,value:'cover_world_palestine',previewColor1:Color(0xff111827),previewColor2:Color(0xff16a34a),collection:'world_2026'),
  StoreProduct(id:'cover_world_celestial',category:'covers',icon:'✨',nameAr:'غلاف سماوي',nameEn:'Celestial Cover',descriptionAr:'غلاف سماوي هادئ.',descriptionEn:'Refined celestial cover.',price:34000,value:'cover_world_celestial',previewColor1:Color(0xff172554),previewColor2:Color(0xfffacc15),collection:'world_2026'),
  StoreProduct(id:'cover_world_crimson',category:'covers',icon:'🔥',nameAr:'غلاف قرمزي',nameEn:'Crimson Cover',descriptionAr:'غلاف قرمزي داكن.',descriptionEn:'Deep crimson cover.',price:34000,value:'cover_world_crimson',previewColor1:Color(0xff21070d),previewColor2:Color(0xffef4444),collection:'world_2026'),
  StoreProduct(id:'cover_world_platinum',category:'covers',icon:'💎',nameAr:'غلاف بلاتيني',nameEn:'Platinum Cover',descriptionAr:'غلاف بلاتيني نظيف.',descriptionEn:'Clean platinum cover.',price:38000,value:'cover_world_platinum',previewColor1:Color(0xff334155),previewColor2:Color(0xffe2e8f0),collection:'world_2026'),
  StoreProduct(id:'cover_world_desert',category:'covers',icon:'🏜️',nameAr:'غلاف الصحراء',nameEn:'Desert Cover',descriptionAr:'ألوان صحراوية دافئة.',descriptionEn:'Warm desert palette.',price:22000,value:'cover_world_desert',previewColor1:Color(0xff422006),previewColor2:Color(0xffd97706),collection:'world_2026'),
  StoreProduct(id:'cover_world_forest',category:'covers',icon:'🌲',nameAr:'غلاف الغابة',nameEn:'Forest Cover',descriptionAr:'غلاف أخضر عميق.',descriptionEn:'Deep forest cover.',price:22000,value:'cover_world_forest',previewColor1:Color(0xff052e16),previewColor2:Color(0xff84cc16),collection:'world_2026'),
  StoreProduct(id:'cover_world_neon',category:'covers',icon:'⚡',nameAr:'غلاف نيون',nameEn:'Neon Cover',descriptionAr:'غلاف نيون حديث.',descriptionEn:'Modern neon cover.',price:42000,value:'cover_world_neon',previewColor1:Color(0xff1e1b4b),previewColor2:Color(0xff22d3ee),collection:'world_2026'),
  StoreProduct(id:'cover_world_sky',category:'covers',icon:'☁️',nameAr:'غلاف السماء',nameEn:'Sky Cover',descriptionAr:'غلاف سماوي فاتح.',descriptionEn:'Bright sky cover.',price:20000,value:'cover_world_sky',previewColor1:Color(0xffe0f2fe),previewColor2:Color(0xff38bdf8),collection:'world_2026'),
  StoreProduct(id:'cover_world_gold',category:'covers',icon:'👑',nameAr:'غلاف الذهب الملكي',nameEn:'Royal Gold Cover',descriptionAr:'غلاف ملكي ذهبي.',descriptionEn:'Royal gold cover.',price:52000,value:'cover_world_gold',previewColor1:Color(0xff211709),previewColor2:Color(0xfff5c75b),collection:'world_2026'),
  StoreProduct(id:'cover_world_lilac',category:'covers',icon:'💜',nameAr:'غلاف الليلك',nameEn:'Lilac Cover',descriptionAr:'غلاف بنفسجي هادئ.',descriptionEn:'Soft lilac cover.',price:26000,value:'cover_world_lilac',previewColor1:Color(0xff2e1065),previewColor2:Color(0xffc4b5fd),collection:'world_2026'),
  StoreProduct(id:'cover_world_ice',category:'covers',icon:'❄️',nameAr:'غلاف الجليد',nameEn:'Ice Cover',descriptionAr:'غلاف جليدي نظيف.',descriptionEn:'Clean ice cover.',price:26000,value:'cover_world_ice',previewColor1:Color(0xff164e63),previewColor2:Color(0xffcffafe),collection:'world_2026'),
  StoreProduct(id:'cover_world_coffee',category:'covers',icon:'☕',nameAr:'غلاف المجلس',nameEn:'Majlis Cover',descriptionAr:'غلاف عربي دافئ.',descriptionEn:'Warm Arabic majlis cover.',price:28000,value:'cover_world_coffee',previewColor1:Color(0xff3f2d20),previewColor2:Color(0xffd6aa59),collection:'world_2026'),
  StoreProduct(id:'cover_world_sapphire',category:'covers',icon:'🔷',nameAr:'غلاف الياقوت',nameEn:'Sapphire Cover',descriptionAr:'غلاف أزرق ملكي.',descriptionEn:'Royal sapphire cover.',price:42000,value:'cover_world_sapphire',previewColor1:Color(0xff172554),previewColor2:Color(0xff3b82f6),collection:'world_2026'),
  StoreProduct(id:'cover_world_mint',category:'covers',icon:'🌿',nameAr:'غلاف النعناع',nameEn:'Mint Cover',descriptionAr:'غلاف أخضر فاتح.',descriptionEn:'Fresh mint cover.',price:20000,value:'cover_world_mint',previewColor1:Color(0xffd1fae5),previewColor2:Color(0xff10b981),collection:'world_2026'),
  StoreProduct(id:'frame_world_gold',category:'frames',icon:'👑',nameAr:'إطار الذهب',nameEn:'Gold Frame',descriptionAr:'إطار دائري ذهبي للبروفايل.',descriptionEn:'Gold circular profile frame.',price:18000,value:'frame_world_gold',previewColor1:Color(0xfff59e0b),previewColor2:Color(0xfffef3c7),collection:'world_2026'),
  StoreProduct(id:'frame_world_neon',category:'frames',icon:'⚡',nameAr:'إطار النيون',nameEn:'Neon Frame',descriptionAr:'إطار نيون متوهج.',descriptionEn:'Neon glow profile frame.',price:24000,value:'frame_world_neon',previewColor1:Color(0xff22d3ee),previewColor2:Color(0xffa855f7),collection:'world_2026'),
  StoreProduct(id:'frame_world_emerald',category:'frames',icon:'💚',nameAr:'إطار الزمرد',nameEn:'Emerald Frame',descriptionAr:'إطار زمردي.',descriptionEn:'Emerald profile frame.',price:22000,value:'frame_world_emerald',previewColor1:Color(0xff10b981),previewColor2:Color(0xffd1fae5),collection:'world_2026'),
  StoreProduct(id:'frame_world_obsidian',category:'frames',icon:'💎',nameAr:'إطار الأوبسيديان',nameEn:'Obsidian Frame',descriptionAr:'إطار أسود ألماسي.',descriptionEn:'Obsidian diamond frame.',price:30000,value:'frame_world_obsidian',previewColor1:Color(0xff020617),previewColor2:Color(0xffcbd5e1),collection:'world_2026'),
];

class V300WorldHome extends StatelessWidget {
  const V300WorldHome({super.key, required this.controller, required this.onTab});
  final AppController controller;
  final ValueChanged<int> onTab;

  @override
  Widget build(BuildContext context) => Stack(children:[
    R9HomeDashboard(controller: controller, onTab: onTab),
    PositionedDirectional(end:16,bottom:16,child:FloatingActionButton.extended(
      heroTag:'world-hub-v300',
      onPressed:(){ HapticFeedback.selectionClick(); Navigator.push(context, MaterialPageRoute(builder:(_)=>V300WorldHubPage(controller:controller))); },
      icon:const Icon(Icons.public_rounded),
      label:Text(L.t(controller.localeCode,'worldHub'),style:const TextStyle(fontWeight:FontWeight.w900)),
    )),
  ]);
}

class V300WorldHubPage extends StatefulWidget {
  const V300WorldHubPage({super.key,required this.controller});
  final AppController controller;
  @override State<V300WorldHubPage> createState()=>_V300WorldHubPageState();
}

class _V300WorldHubPageState extends State<V300WorldHubPage> {
  Map<String,dynamic>? party; bool busy=false;
  @override void initState(){super.initState(); if(widget.controller.serverConnected) unawaited(_loadParty());}
  Future<void> _loadParty() async { try{final r=await widget.controller.api.myPartyV300(); if(mounted)setState(()=>party=r['party'] is Map?Map<String,dynamic>.from(r['party'] as Map):null);}catch(_){}}
  Future<void> _createParty() async { setState(()=>busy=true); try{final r=await widget.controller.api.createPartyV300(gameKey:widget.controller.homeGames.first.id); if(mounted)setState(()=>party=r['party'] is Map?Map<String,dynamic>.from(r['party'] as Map):null); HapticFeedback.mediumImpact();}catch(e){if(mounted)showToast(context,friendlyErrorMessage(e,widget.controller.localeCode));} if(mounted)setState(()=>busy=false); }
  @override Widget build(BuildContext context){
    final c=widget.controller;
    return Scaffold(appBar:AppBar(title:Text(L.t(c.localeCode,'worldHub'))),body:ListView(padding:const EdgeInsets.all(16),children:[
      SizedBox(height:116,child:Center(child:Lottie.asset('assets/lottie/world/world_pulse.json',repeat:true))),
      Text(L.t(c.localeCode,'worldExperience'),textAlign:TextAlign.center,style:TextStyle(fontSize:24,fontWeight:FontWeight.w900,color:Theme.of(context).colorScheme.primary)),
      const SizedBox(height:16),
      LayoutBuilder(builder:(context,box){final wide=box.maxWidth>760; final cards=<Widget>[
        _V300HubCard(icon:Icons.flash_on_rounded,title:L.t(c.localeCode,'quickMatch'),subtitle:L.t(c.localeCode,'matchmaking'),onTap:()=>showGameLobby(context,c,c.homeGames.first)),
        _V300HubCard(icon:Icons.groups_2_rounded,title:party==null?L.t(c.localeCode,'createParty'):L.t(c.localeCode,'myParty'),subtitle:party?['code']?.toString()??L.t(c.localeCode,'partyHint'),onTap:busy?null:_createParty),
        _V300HubCard(icon:Icons.visibility_rounded,title:L.t(c.localeCode,'spectate'),subtitle:L.t(c.localeCode,'spectateHint'),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>R11SocialWorldPage(controller:c)))),
        _V300HubCard(icon:Icons.wifi_protected_setup_rounded,title:L.t(c.localeCode,'reconnect'),subtitle:L.t(c.localeCode,'reconnectHint'),onTap:c.activeRoomCode==null?null:() async {try{await c.api.reconnectRoomV300(c.activeRoomCode!);if(context.mounted)showToast(context,L.t(c.localeCode,'reconnect'));}catch(e){if(context.mounted)showToast(context,friendlyErrorMessage(e,c.localeCode));}}),
      ]; return GridView.count(crossAxisCount:wide?4:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),mainAxisSpacing:10,crossAxisSpacing:10,childAspectRatio:wide?1.25:.95,children:cards);}),
      const SizedBox(height:16),
      R9Section(child:Wrap(spacing:12,runSpacing:10,children:[Chip(avatar:const Icon(Icons.security_rounded,size:16),label:Text(L.t(c.localeCode,'afkProtection'))),Chip(avatar:const Icon(Icons.smart_toy_outlined,size:16),label:Text(L.t(c.localeCode,'serverControl'))),Chip(avatar:const Icon(Icons.emoji_events_outlined,size:16),label:Text(L.t(c.localeCode,'seasonal'))),Chip(avatar:const Icon(Icons.speed_rounded,size:16),label:Text(L.t(c.localeCode,'matchmaking')))])),
    ]));
  }
}

class _V300HubCard extends StatelessWidget{
  const _V300HubCard({required this.icon,required this.title,required this.subtitle,this.onTap});
  final IconData icon; final String title,subtitle; final VoidCallback? onTap;
  @override Widget build(BuildContext context)=>InkWell(onTap:onTap,borderRadius:BorderRadius.circular(24),child:Ink(padding:const EdgeInsets.all(16),decoration:BoxDecoration(borderRadius:BorderRadius.circular(24),gradient:LinearGradient(colors:[Theme.of(context).colorScheme.primary.withValues(alpha:.14),Theme.of(context).colorScheme.surface]),border:Border.all(color:Theme.of(context).colorScheme.primary.withValues(alpha:.18))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon,color:Theme.of(context).colorScheme.primary,size:30),const Spacer(),Text(title,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:15)),const SizedBox(height:5),Text(subtitle,maxLines:3,overflow:TextOverflow.ellipsis,style:TextStyle(fontSize:10,height:1.35,color:Theme.of(context).colorScheme.onSurface.withValues(alpha:.65)))])));
}

class V300AdminWorldOpsPanel extends StatefulWidget{
  const V300AdminWorldOpsPanel({super.key,required this.controller}); final AppController controller;
  @override State<V300AdminWorldOpsPanel> createState()=>_V300AdminWorldOpsPanelState();
}
class _V300AdminWorldOpsPanelState extends State<V300AdminWorldOpsPanel>{Map<String,dynamic>? data;bool loading=false;@override void initState(){super.initState();if(widget.controller.serverConnected)unawaited(load());}Future<void> load()async{setState(()=>loading=true);try{data=await widget.controller.api.adminEconomyAuditV300(refresh:true);}catch(e){if(mounted)showToast(context,e.toString());}if(mounted)setState(()=>loading=false);}@override Widget build(BuildContext context){final s=data?['summary'] is Map?Map<String,dynamic>.from(data!['summary'] as Map):<String,dynamic>{};final events=data?['events'] is List?data!['events'] as List:const[];return RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(12),children:[Wrap(spacing:8,runSpacing:8,children:[_AdminMetric(icon:'🛡️',label:'Open audit',value:'${s['open']??0}'),_AdminMetric(icon:'🚨',label:'Critical',value:'${s['critical']??0}'),_AdminMetric(icon:'⚠️',label:'High risk',value:'${s['high']??0}'),_AdminMetric(icon:'📊',label:'24h',value:'${s['last_24h']??0}')]),const SizedBox(height:12),const _AdminInfo(text:'WORLD OPS يجمع تدقيق الاقتصاد مع مؤشرات الجلسات، الحماية من إساءة الاستخدام، ومراجعة المعاملات عالية المخاطر. كل الحكم المالي يبقى خادميًا.'),const SizedBox(height:8),if(loading)const LinearProgressIndicator(),...events.take(80).map((e){final m=e is Map?Map<String,dynamic>.from(e):<String,dynamic>{};return Card(child:ListTile(leading:CircleAvatar(child:Text('${m['risk_score']??0}')),title:Text(m['type']?.toString()??'audit'),subtitle:Text('status: ${m['status']??'open'} • user ${m['user_id']??'-'}'),trailing:const Icon(Icons.chevron_right)));})]));}}
