#!/usr/bin/env python3
from pathlib import Path
import json,re,sys
ROOT=Path(__file__).resolve().parents[1]
def text(rel): return (ROOT/rel).read_text(encoding='utf-8',errors='ignore')
def ok(cond,msg):
    if not cond:
        print('[FAIL]',msg); sys.exit(1)
    print('[PASS]',msg)
meta=json.loads(text('RELEASE_VERSION.json'))
ok(int(meta.get('build',0))>=304,'release remains build 304 or newer')
main=text('flutter_app/lib/main.dart'); v304=text('flutter_app/lib/v304_vertical_legend.dart')
ok("part 'v304_vertical_legend.dart';" in main,'Flutter B304 module is wired')
ok("b304ActiveLocaleCodes = <String>{'ar', 'en'}" in v304 and "b304FutureLocaleCodes = <String>{'de', 'tr', 'fr', 'es'}" in v304,'Arabic/English active with future locale registry')
ok("supportedLocales: const [Locale('ar'), Locale('en')]" in main.replace('\n',' ') or ("Locale('ar')" in main and "Locale('en')" in main),'Flutter exposes Arabic and English active locales')
ok(all(g in v304 for g in ("'jackaroo'", "'backgammon'", "'domino'", "'chess'")),'removed games are banned from customer catalog')
ok(v304.count("StoreProduct(id:'b304_table_")==10,'exactly ten B304 vertical table products exist')
ok("const String b304CardBackId = 'b304_cardback_vertical'" in v304,'one B304 card-back identity is canonical')
ok(v304.count("category:'profile_colors'")>=6 and 'durationDays:30' in v304,'real 30-day profile colors are available')
ok('return const B304HomeDashboard' not in main and 'B304HomeDashboard' in main,'compact B304 home is active')
ok('R12CompetitiveArenaPage' in v304 and 'R11SocialWorldPage' not in v304,'B304 home prioritizes Competitions instead of Social World')
ok("if (p.category == 'badges' || p.category == 'effects')" in main or ("'badges'" not in re.search(r'List<String> get storeCategories.*?;',main,re.S).group(0) if re.search(r'List<String> get storeCategories.*?;',main,re.S) else True),'badges/effects are not customer store categories')
ok('WARQNAA BOOST' not in (main+text('flutter_app/lib/v183_overhaul.dart')+text('backend-laravel/resources/views/store/index.blade.php')).upper(),'legacy booster branding is removed from active UI source')
langs=text('backend-laravel/config/warqna_languages.php')
ok("'ar'" in langs and "'en'" in langs and all(f"'{x}'" not in langs for x in ('de','tr','fr','es')),'backend active locales are Arabic and English only')
future=text('backend-laravel/config/warqna_languages_future.php')
ok(all(f"'{x}'" in future for x in ('de','tr','fr','es')),'future language metadata remains extensible')
cat=text('backend-laravel/app/Services/Games/GameCatalog.php')
block=cat[cat.index('public static function all'):cat.index('public static function customerKeys')]
ok(all(f"'{g}'" not in block for g in ('jackaroo','backgammon','domino','chess')),'removed games are absent from Laravel customer game catalog')
ok("'basra'=>" in block and "'min'=>2,'max'=>2" in block,'Basra is exactly two-player')
ok("'tarneeb'=>" in block and 'طلب 7–13' in block and 'Pass' in cat,'Tarneeb 7–13 and Pass contract is documented')
deck=text('backend-laravel/app/Services/GameEngine/DeckFactory.php')
ok('random_int(0,$i)' in deck and 'balancedDeal' in deck and 'weakest hand is strongest' in deck,'secure symmetric balanced-deal engine is preserved')
ok((ROOT/'backend-laravel/tools/test-v304-fair-deal.php').exists(),'thousands-scenario fair-deal certification exists')
life=text('backend-laravel/app/Services/Gameplay/MatchLifecycleService.php')
ok('ABANDONED_SECONDS=600' in life.replace(' ',''),'abandoned matches expire after 10 minutes')
mobile=text('backend-laravel/app/Http/Controllers/MobileApiController.php')
ok('dailyLimit = min(8' in mobile and 'claimNumber = min(8' in mobile and "'temporary_reward'=>$temporary" in mobile,'progressive eight-step rewarded ads are server-authoritative')
store=text('backend-laravel/app/Services/WarqnaPro/StoreCatalogService.php')
ok('syncB304VerticalLegend' in store and "whereIn('category',['badge','effect'])" in store,'B304 store deactivates legacy tables/cardbacks/effects/badges')
level=text('backend-laravel/app/Services/Leveling/XpService.php')
ok('grantTwoTemporaryRewards' in level and 'addDays(7)' in level,'each level-up can grant two seven-day temporary store rewards')
challenge=text('backend-laravel/app/Services/WarqnaPro/ChallengeRoadService.php')
ok(('b304_table_phoenix' in challenge and 'b304_profile_aurora_30d' in challenge) or (ROOT/'flutter_app/lib/v305_single_table.dart').exists(),'B304 challenge history is preserved or superseded by V305 single-table rewards')
user=text('backend-laravel/app/Models/User.php')
ok("PRIMARY_ADMIN_DISPLAY_BALANCE = '1000000000000000000000000000000'" in user and 'isPrimaryAdmin' in user,'primary admin unlimited display balance and role protection are preserved')
setup=text('backend-laravel/app/Console/Commands/SetupLocalAdmins.php')
ok('WARQNAA_LOCAL_ADMIN_PASSWORD' in setup and 'WARQNAA_LOCAL_DEPUTY_PASSWORD' in setup,'privileged credentials are provisioned from local environment, not source literals')
ok((ROOT/'tools/check_git_privacy_v304.py').exists(),'B304 Git privacy gate exists')
runtime=text('backend-laravel/tests/Feature/V304VerticalLegendTest.php')
ok('test_customer_catalog_hides_removed_games_and_basra_is_two_player' in runtime and 'test_primary_admin_role_is_durable_after_username_change' in runtime,'B304 focused Laravel runtime regression suite exists')
for wf in ('backend-ci.yml','global-release.yml'):
    ok('V304VerticalLegendTest' in text('.github/workflows/'+wf),f'B304 runtime regression is wired into {wf}')

print('V304 VERTICAL LEGEND CONTRACT: PASS')
