#!/usr/bin/env python3
"""Verify exact package versions in a Dart/Flutter pubspec.lock file.

This intentionally uses only the Python standard library and does not assume
that the `version:` line is close to the package name. It therefore remains
stable when Pub adds description/source metadata between those fields.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

PACKAGE_HEADER = re.compile(r"^  ([A-Za-z0-9_]+):\s*$")
VERSION_LINE = re.compile(r'^    version:\s*["\']?([^"\'\s]+)["\']?\s*$')
DEPENDENCY_LINE = re.compile(r'^    dependency:\s*["\']?([^"\']+)["\']?\s*$')


def parse_lock(path: Path) -> dict[str, dict[str, str]]:
    if not path.is_file():
        raise FileNotFoundError(f"Lock file not found: {path}")

    packages: dict[str, dict[str, str]] = {}
    current: str | None = None
    in_packages = False

    for raw in path.read_text(encoding="utf-8").splitlines():
        if raw == "packages:":
            in_packages = True
            current = None
            continue
        if not in_packages:
            continue

        # A new top-level key means the packages section has ended.
        if raw and not raw.startswith(" "):
            break

        header = PACKAGE_HEADER.match(raw)
        if header:
            current = header.group(1)
            packages[current] = {}
            continue

        if current is None:
            continue

        version = VERSION_LINE.match(raw)
        if version:
            packages[current]["version"] = version.group(1)
            continue

        dependency = DEPENDENCY_LINE.match(raw)
        if dependency:
            packages[current]["dependency"] = dependency.group(1)

    return packages


def parse_expected(values: list[str]) -> dict[str, str]:
    expected: dict[str, str] = {}
    for item in values:
        if "=" not in item:
            raise ValueError(f"Expected package=version, got: {item}")
        name, version = item.split("=", 1)
        name, version = name.strip(), version.strip()
        if not name or not version:
            raise ValueError(f"Expected package=version, got: {item}")
        expected[name] = version
    return expected


def self_test() -> None:
    sample = """# Generated by pub
packages:
  flutter_webrtc:
    dependency: "direct main"
    description:
      name: flutter_webrtc
      sha256: abc
      url: "https://pub.dev"
    source: hosted
    version: "1.4.0"
  google_mobile_ads:
    dependency: "direct main"
    description:
      name: google_mobile_ads
      sha256: def
      url: "https://pub.dev"
    source: hosted
    version: "7.0.0"
sdks:
  dart: ">=3.9.0 <4.0.0"
"""
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "pubspec.lock"
        path.write_text(sample, encoding="utf-8")
        parsed = parse_lock(path)
        assert parsed["google_mobile_ads"]["version"] == "7.0.0"
        assert parsed["flutter_webrtc"]["version"] == "1.4.0"
    print("[OK] verify_flutter_lock self-test")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("lockfile", nargs="?", type=Path)
    parser.add_argument("expected", nargs="*")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        self_test()
        return 0
    if args.lockfile is None or not args.expected:
        parser.error("provide pubspec.lock and one or more package=version checks")

    try:
        expected = parse_expected(args.expected)
        packages = parse_lock(args.lockfile)
    except (OSError, ValueError) as exc:
        print(f"[FAIL] {exc}", file=sys.stderr)
        return 1

    failed = False
    for package, wanted in expected.items():
        info = packages.get(package)
        if info is None:
            print(f"[FAIL] {package} is missing from {args.lockfile}", file=sys.stderr)
            failed = True
            continue
        actual = info.get("version")
        if actual != wanted:
            print(
                f"[FAIL] {package}: expected {wanted}, resolved {actual or '<missing version>'}",
                file=sys.stderr,
            )
            failed = True
            continue
        dependency = info.get("dependency", "unknown")
        print(f"[OK] {package} {actual} ({dependency})")

    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
